# 01. Exploration of instance metadata

Load `data/metadata.csv` and explore distributions. Filter criteria can be adjusted later in YAML.

In [1]:
import pandas as pd

metadata_path = "../data/metadata.csv"
df = pd.read_csv(metadata_path)
df.head()

,name,num_vars,num_binary,num_integer,num_continuous,num_constraints,obj_sense
0,10teams,2025,1800,0,225,230,min
1,22433,429,231,0,198,198,min
2,23588,368,231,0,137,137,min
3,2club200v15p5scn,200,200,0,0,17013,min
4,30_70_45_05_100,10772,10771,0,1,12050,min

In [2]:
df.select_dtypes(include='number').describe()

,num_vars,num_binary,num_integer,num_continuous,num_constraints
count,91.000000,91.000000,91.000000,91.000000,9.100000e+01
mean,39962.758242,23134.571429,1154.351648,15673.835165,3.227207e+04
std,104213.062396,56393.771744,8337.480395,69300.580056,1.406205e+05
min,100.000000,28.000000,0.000000,0.000000,3.000000e+01
25%,1791.000000,501.500000,0.000000,0.000000,6.495000e+02
50%,4907.000000,3283.000000,0.000000,52.000000,3.285000e+03
75%,15446.500000,12496.000000,0.000000,1250.000000,1.249850e+04
max,590519.000000,393800.000000,78288.000000,467905.000000,1.299953e+06

In [6]:
print("Objective senses:")
print(df["obj_sense"].value_counts(dropna=False))

Objective senses:
obj_sense
min    91
Name: count, dtype: int64